/*******************************************************************
 * Kysely ABAC Plugin DB Schema
 * DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING
 *
 * This file is auto-generated by the kysely-codegen Plugin.
 * It defines the database schema for the ABAC plugin used in the application.
 * The schema includes tables for access requests, accounts, actions, attributes,
 * policies, resources, roles, sessions, users, and more.
 * Each table has its own set of fields, types, and relationships.
 ******************************************************************/

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
	? ColumnType<S, I | undefined, U>
	: ColumnType<T, T | undefined, T>;

export interface AccessRequest {
	action_id: string;
	applied_policies: string | null;
	created_at: Date | null;
	decision: string | null;
	id: string;
	processing_time_ms: number | null;
	request_context: string | null;
	resource_id: string;
	user_id: string;
}

export interface Account {
	access_token: string | null;
	access_token_expires_at: Date | null;
	account_id: string;
	created_at: Date;
	id: string;
	id_token: string | null;
	password: string | null;
	provider_id: string;
	refresh_token: string | null;
	refresh_token_expires_at: Date | null;
	scope: string | null;
	updated_at: Date;
	user_id: string;
}

export interface ActionAttribute {
	action_id: string;
	attribute_id: string;
	created_at: Date | null;
	id: string;
	value: string;
}

export interface Actions {
	created_at: Date | null;
	description: string | null;
	id: string;
	name: string;
	resource_type_id: string;
}

export interface Attribute {
	category: string;
	created_at: Date | null;
	description: string | null;
	id: string;
	name: string;
	type: string;
	updated_at: Date | null;
	valid_values: string | null;
}

export interface DynamicAttribute {
	attribute_id: string;
	cache_timeout_minutes: Generated<number | null>;
	computation_rule: string;
	created_at: Date | null;
	id: string;
	is_active: Generated<number | null>;
	name: string;
	updated_at: Date | null;
}

export interface EnvironmentAttribute {
	attribute_id: string;
	created_at: Date | null;
	id: string;
	name: string;
	updated_at: Date | null;
	valid_from: Date | null;
	valid_to: Date | null;
	value: string;
}

export interface Policy {
	created_at: Date | null;
	description: string | null;
	effect: string;
	id: string;
	is_active: Generated<number | null>;
	name: string;
	policy_set_id: string;
	priority: number;
	rules: string;
	updated_at: Date | null;
}

export interface PolicyRule {
	attribute_id: string;
	created_at: Date | null;
	group_id: string | null;
	id: string;
	logical_operator: string | null;
	operator: string;
	policy_id: string;
	value: string;
}

export interface PolicySet {
	created_at: Date | null;
	description: string | null;
	id: string;
	is_active: Generated<number | null>;
	name: string;
	priority: number;
	updated_at: Date | null;
}

export interface PolicyTarget {
	attribute_id: string;
	created_at: Date | null;
	id: string;
	operator: string;
	policy_id: string;
	target_id: string;
	target_type: string;
	value: string;
}

export interface Resource {
	created_at: Date | null;
	id: string;
	name: string;
	owner_id: string;
	resource_id: string;
	resource_type_id: string;
}

export interface ResourceAttribute {
	attribute_id: string;
	created_at: Date | null;
	id: string;
	resource_id: string;
	updated_at: Date | null;
	value: string;
}

export interface ResourceType {
	created_at: Date | null;
	description: string | null;
	id: string;
	name: string;
	table_name: string;
}

export interface Role {
	color: string | null;
	created_at: Date | null;
	description: string | null;
	id: string;
	name: string;
	updated_at: Date | null;
}

export interface RoleAttribute {
	attribute_id: string;
	created_at: Date | null;
	id: string;
	role_id: string;
	updated_at: Date | null;
	value: string;
}

export interface Session {
	created_at: Date;
	expires_at: Date;
	id: string;
	ip_address: string | null;
	token: string;
	updated_at: Date;
	user_agent: string | null;
	user_id: string;
}

export interface User {
	created_at: Date;
	email: string;
	email_verified: number;
	id: string;
	image: string | null;
	name: string;
	role_id: string;
	updated_at: Date;
}

export interface UserAttribute {
	attribute_id: string;
	created_at: Date | null;
	id: string;
	updated_at: Date | null;
	user_id: string;
	value: string;
}

export interface Verification {
	created_at: Date | null;
	expires_at: Date;
	id: string;
	identifier: string;
	updated_at: Date | null;
	value: string;
}

export interface Database {
	access_request: AccessRequest;
	account: Account;
	action_attribute: ActionAttribute;
	actions: Actions;
	attribute: Attribute;
	dynamic_attribute: DynamicAttribute;
	environment_attribute: EnvironmentAttribute;
	policy: Policy;
	policy_rule: PolicyRule;
	policy_set: PolicySet;
	policy_target: PolicyTarget;
	resource: Resource;
	resource_attribute: ResourceAttribute;
	resource_type: ResourceType;
	role: Role;
	role_attribute: RoleAttribute;
	session: Session;
	user: User;
	user_attribute: UserAttribute;
	verification: Verification;
}
